/**
 * Editing operations on a flowchart spec.
 *
 * Pure functions over a draft, deliberately kept out of the components: the
 * studio, the blog-editor widget and the keyboard shortcuts all perform the
 * same handful of edits, and "add a box" meaning something subtly different
 * in each of them is how an editor grows inconsistent.
 *
 * Every one of these mutates a draft in place. `useFlowchartDoc` owns the
 * cloning, so nothing here has to think about immutability.
 */

import { edgeKey, type FlowEdge, type FlowNode, type FlowNodeType, type FlowchartSpec } from "./types";

let counter = 0;

/** Unique enough for a document that only ever lives in one browser tab. */
export function newId(): string {
  counter += 1;
  return `n${Date.now().toString(36)}${counter.toString(36)}`;
}

export function deepClone(spec: FlowchartSpec): FlowchartSpec {
  return JSON.parse(JSON.stringify(spec)) as FlowchartSpec;
}

/** The label a fresh box of each shape starts with. */
export function defaultTextFor(type: FlowNodeType): string {
  switch (type) {
    case "start":
      return "Start";
    case "end":
      return "End";
    case "decision":
      return "Condition?";
    case "io":
      return "Read input";
    case "group":
      return "Stage";
    default:
      return "Do something";
  }
}

/**
 * Where a new box goes when there is a box selected.
 *
 * Downstream of the selection along the direction of flow, so that the
 * common act of building a chart - add a step, add the next step, add the
 * next - lays a chain out in reading order without anybody positioning
 * anything. Only used when the selected box has been hand-placed; otherwise
 * the new box gets no position at all and the auto-layout does the work.
 */
function nextTo(anchor: FlowNode, direction: "TB" | "LR"): { x: number; y: number } | undefined {
  if (!anchor.position) return undefined;
  return direction === "LR"
    ? { x: anchor.position.x + 200, y: anchor.position.y }
    : { x: anchor.position.x, y: anchor.position.y + 130 };
}

export interface AddNodeResult {
  id: string;
  /** True when the new box was wired up to the selection. */
  connected: boolean;
}

/**
 * Adds a box, and connects it to the current selection when there is one.
 *
 * The auto-connect is the point. Building a chart is overwhelmingly "and then
 * this happens", so the tool should assume that and let the rare exception be
 * undone, rather than making every single step a two-part act of creating a
 * box and then separately joining it up.
 */
export function addNode(
  draft: FlowchartSpec,
  type: FlowNodeType,
  selectedId: string | null,
  /**
   * Generated by the caller, not here.
   *
   * The document applies these through a state updater, which React invokes
   * twice in development. Minting the id inside would hand the two runs
   * different ids and let whichever one React kept disagree with the
   * selection the caller had already made.
   */
  id: string,
): AddNodeResult {
  const anchor = selectedId ? draft.nodes.find((n) => n.id === selectedId) : undefined;

  const node: FlowNode = {
    id,
    type,
    text: defaultTextFor(type),
    ...(type === "group" ? { groupLayout: "column" as const } : {}),
  };

  // A new box inside a group belongs to that group: it is the only reading of
  // "add a step while a container is selected" that is not surprising.
  if (anchor?.type === "group" && type !== "group") node.parentId = anchor.id;
  else if (anchor && anchor.type !== "group") {
    const position = nextTo(anchor, draft.direction ?? "TB");
    if (position) node.position = position;
    if (anchor.parentId) node.parentId = anchor.parentId;
    if (anchor.lane) node.lane = anchor.lane;
  }

  draft.nodes.push(node);

  // Terminals and containers are not "the next step", so they are not wired
  // up automatically: a start node with an arrow into it is wrong, and an
  // arrow into a group is meaningless.
  const shouldConnect =
    Boolean(anchor) &&
    anchor!.type !== "group" &&
    anchor!.type !== "end" &&
    type !== "start" &&
    type !== "group";

  if (shouldConnect) connect(draft, anchor!.id, id);

  return { id, connected: shouldConnect };
}

/** Adds an arrow, unless the identical one is already there. */
export function connect(draft: FlowchartSpec, from: string, to: string, label?: string): boolean {
  if (from === to) return false;
  const trimmed = label?.trim() || undefined;
  if (draft.edges.some((e) => e.from === from && e.to === to && e.label === trimmed)) return false;
  draft.edges.push({ from, to, ...(trimmed ? { label: trimmed } : {}) });
  return true;
}

/**
 * Removes boxes and arrows together, and cleans up everything that pointed at
 * them: arrows to a deleted box, walkthrough steps naming one, and children
 * of a deleted group (freed rather than deleted, since they are real steps
 * that happened to be filed under a container).
 */
export function removeElements(draft: FlowchartSpec, nodeIds: string[], edgeIds: string[]): void {
  const doomed = new Set(nodeIds);

  if (doomed.size > 0) {
    for (const n of draft.nodes) if (n.parentId && doomed.has(n.parentId)) delete n.parentId;
    draft.nodes = draft.nodes.filter((n) => !doomed.has(n.id));
    draft.edges = draft.edges.filter((e) => !doomed.has(e.from) && !doomed.has(e.to));
  }

  if (edgeIds.length > 0) {
    const keys = new Set(edgeIds);
    draft.edges = draft.edges.filter((e) => !keys.has(edgeKey(e)));
  }

  if (draft.walkthrough) {
    const liveNodes = new Set(draft.nodes.map((n) => n.id));
    const liveEdges = new Set(draft.edges.map(edgeKey));
    draft.walkthrough = draft.walkthrough.filter(
      (s) => (!s.node || liveNodes.has(s.node)) && (!s.edge || liveEdges.has(s.edge)),
    );
  }
}

export function findEdge(spec: FlowchartSpec, key: string): FlowEdge | undefined {
  return spec.edges.find((e) => edgeKey(e) === key);
}

/** Index of an arrow by key, for edits that have to write back in place. */
export function edgeIndex(spec: FlowchartSpec, key: string): number {
  return spec.edges.findIndex((e) => edgeKey(e) === key);
}

/** Drops every hand-placed position, handing the chart back to the layout. */
export function clearPositions(draft: FlowchartSpec): void {
  for (const n of draft.nodes) delete n.position;
}

/** How many boxes are pinned by hand. Drives whether "Auto-layout" is offered. */
export function placedCount(spec: FlowchartSpec): number {
  return spec.nodes.filter((n) => n.position).length;
}

export const EMPTY_CHART: FlowchartSpec = {
  title: "Untitled chart",
  direction: "TB",
  nodes: [
    { id: "start", type: "start", text: "Start" },
    { id: "step", type: "process", text: "Do something" },
    { id: "end", type: "end", text: "End" },
  ],
  edges: [
    { from: "start", to: "step" },
    { from: "step", to: "end" },
  ],
};
