/**
 * Flowcharts for each sorting algorithm.
 *
 * Each one is written to match the code shown in that algorithm's tutorial
 * page line for line, so a reader can hold the two side by side. Where the
 * code has a loop, the chart has a back edge; where the code has an `if`,
 * the chart has a labelled decision.
 *
 * Colour is used sparingly and always means something. Violet marks a
 * recursive call, blue marks the step that actually moves data, and copper
 * marks a decision. A chart where every box is a different colour teaches
 * nothing, so anything that is merely bookkeeping stays neutral.
 *
 * The recursive algorithms are the awkward ones. A flowchart has no way to
 * express "call yourself", so merge and quick sort are drawn as the shape of
 * a single call, with the recursive steps marked as violet process boxes.
 * That limitation is worth naming in the lesson rather than papering over.
 *
 * Three charts carry a `walkthrough`: a recorded path through the diagram,
 * captioned against a concrete array. Those are the three where the control
 * flow is genuinely hard to hold in your head, and being able to press play
 * on the real sequence is worth more than another paragraph of prose.
 */

import type { FlowchartSpec } from "./types";

export const BUBBLE_SORT_CHART: FlowchartSpec = {
  title: "Bubble sort",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "Start" },
    { id: "init", type: "process", text: "pass = 0", note: "One pass per element, minus one." },
    { id: "outer", type: "decision", text: "pass < n-1 ?" },
    {
      id: "reset",
      type: "process",
      text: "i = 0\nswapped = false",
      note: "swapped is what allows the early exit. Clearing it at the top of every pass is what makes it mean 'did anything move during this pass', rather than 'ever'.",
    },
    {
      id: "inner",
      type: "decision",
      text: "i < n-1-pass ?",
      note: "The tail is already sorted, so each pass looks at one fewer element.",
    },
    { id: "cmp", type: "decision", text: "a[i] > a[i+1] ?" },
    {
      id: "swap",
      type: "process",
      text: "swap a[i], a[i+1]\nswapped = true",
      accent: "blue",
      note: "The only step that moves data. Everything else in this chart is bookkeeping around it.",
    },
    { id: "inc-i", type: "process", text: "i = i + 1" },
    {
      id: "check",
      type: "decision",
      text: "swapped ?",
      accent: "amber",
      badge: "!",
      note: "A whole pass with no swaps means the array is already ordered, so the remaining passes would all do nothing. This one test is what makes bubble sort O(n) on sorted input.",
    },
    { id: "inc-pass", type: "process", text: "pass = pass + 1" },
    { id: "end", type: "end", text: "Sorted" },
  ],
  edges: [
    { id: "e1", from: "start", to: "init" },
    { id: "e2", from: "init", to: "outer" },
    { id: "e3", from: "outer", to: "reset", label: "yes" },
    { id: "e4", from: "outer", to: "end", label: "no" },
    { id: "e5", from: "reset", to: "inner" },
    { id: "e6", from: "inner", to: "cmp", label: "yes" },
    { id: "e7", from: "inner", to: "check", label: "no" },
    { id: "e8", from: "cmp", to: "swap", label: "yes" },
    { id: "e9", from: "cmp", to: "inc-i", label: "no" },
    { id: "e10", from: "swap", to: "inc-i" },
    { id: "e11", from: "inc-i", to: "inner" },
    { id: "e12", from: "check", to: "inc-pass", label: "yes" },
    { id: "e13", from: "check", to: "end", label: "no" },
    { id: "e14", from: "inc-pass", to: "outer" },
  ],
  walkthrough: [
    { node: "start", caption: "Sorting [5, 1, 4]. Three elements, so n = 3." },
    { node: "init", caption: "pass = 0. The outer loop will run at most n-1 = 2 times." },
    { node: "outer", caption: "pass < 2 ? Yes, so start a pass." },
    { node: "reset", caption: "i = 0, swapped = false. Every pass starts by forgetting what the last one did." },
    { node: "inner", caption: "i < n-1-pass, that is 0 < 2 ? Yes." },
    { node: "cmp", caption: "a[0] = 5, a[1] = 1. Is 5 > 1 ? Yes, they are out of order." },
    { node: "swap", caption: "Swap them. The array is now [1, 5, 4] and swapped = true." },
    { node: "inc-i", caption: "i = 1." },
    { node: "inner", caption: "1 < 2 ? Yes, keep going." },
    { node: "cmp", caption: "a[1] = 5, a[2] = 4. Is 5 > 4 ? Yes." },
    { node: "swap", caption: "Swap. The array is [1, 4, 5]. The largest value has bubbled to the end." },
    { node: "inc-i", caption: "i = 2." },
    { node: "inner", caption: "2 < 2 ? No. This pass is over." },
    { node: "check", caption: "swapped ? Yes, this pass moved things, so the array might still be unsorted." },
    { node: "inc-pass", caption: "pass = 1." },
    { node: "outer", caption: "1 < 2 ? Yes, one more pass." },
    { node: "reset", caption: "i = 0, swapped = false again." },
    { node: "inner", caption: "i < n-1-pass is 0 < 1 ? Yes. Note the range shrank: a[2] is already final." },
    { node: "cmp", caption: "a[0] = 1, a[1] = 4. Is 1 > 4 ? No, already in order." },
    { node: "inc-i", caption: "i = 1. Nothing moved." },
    { node: "inner", caption: "1 < 1 ? No. Pass over." },
    { node: "check", caption: "swapped ? No. Nothing moved all pass, so the array is sorted." },
    { node: "end", caption: "Done in two passes instead of the full n-1, purely because of that swapped flag." },
  ],
  interactive: { walkthrough: true },
};

export const SELECTION_SORT_CHART: FlowchartSpec = {
  title: "Selection sort",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "Start" },
    { id: "init", type: "process", text: "i = 0" },
    { id: "outer", type: "decision", text: "i < n-1 ?" },
    {
      id: "setmin",
      type: "process",
      text: "min = i\nj = i + 1",
      note: "Assume the first unsorted element is the smallest until proven otherwise.",
    },
    { id: "inner", type: "decision", text: "j < n ?" },
    { id: "cmp", type: "decision", text: "a[j] < a[min] ?" },
    {
      id: "newmin",
      type: "process",
      text: "min = j",
      note: "Only the index is recorded. Nothing moves during the scan, which is exactly why selection sort does so few writes.",
    },
    { id: "inc-j", type: "process", text: "j = j + 1" },
    {
      id: "swap",
      type: "process",
      text: "swap a[i], a[min]",
      accent: "blue",
      note: "Exactly one swap per outer iteration, which is the algorithm's whole selling point: n-1 writes total, no matter how scrambled the input.",
    },
    { id: "inc-i", type: "process", text: "i = i + 1" },
    { id: "end", type: "end", text: "Sorted" },
  ],
  edges: [
    { from: "start", to: "init" },
    { from: "init", to: "outer" },
    { from: "outer", to: "setmin", label: "yes" },
    { from: "outer", to: "end", label: "no" },
    { from: "setmin", to: "inner" },
    { from: "inner", to: "cmp", label: "yes" },
    { from: "inner", to: "swap", label: "no" },
    { from: "cmp", to: "newmin", label: "yes" },
    { from: "cmp", to: "inc-j", label: "no" },
    { from: "newmin", to: "inc-j" },
    { from: "inc-j", to: "inner" },
    { from: "swap", to: "inc-i" },
    { from: "inc-i", to: "outer" },
  ],
};

export const INSERTION_SORT_CHART: FlowchartSpec = {
  title: "Insertion sort",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "Start" },
    {
      id: "init",
      type: "process",
      text: "i = 1",
      note: "A single element is already a sorted prefix, so start at the second.",
    },
    { id: "outer", type: "decision", text: "i < n ?" },
    {
      id: "take",
      type: "process",
      text: "value = a[i]\nj = i - 1",
      note: "value is held outside the array while the shifting happens, which is what frees the slot it used to occupy.",
    },
    { id: "inner", type: "decision", text: "j >= 0 and\na[j] > value ?" },
    {
      id: "shift",
      type: "process",
      text: "a[j+1] = a[j]\nj = j - 1",
      accent: "blue",
      note: "Shifting, not swapping. Each step moves one element right by one, and a swap would cost three writes where this costs one.",
    },
    {
      id: "place",
      type: "process",
      text: "a[j+1] = value",
      accent: "blue",
      note: "The gap left by shifting is exactly where value belongs.",
    },
    { id: "inc-i", type: "process", text: "i = i + 1" },
    { id: "end", type: "end", text: "Sorted" },
  ],
  edges: [
    { from: "start", to: "init" },
    { from: "init", to: "outer" },
    { from: "outer", to: "take", label: "yes" },
    { from: "outer", to: "end", label: "no" },
    { from: "take", to: "inner" },
    { from: "inner", to: "shift", label: "yes" },
    { from: "inner", to: "place", label: "no" },
    { from: "shift", to: "inner" },
    { from: "place", to: "inc-i" },
    { from: "inc-i", to: "outer" },
  ],
};

export const MERGE_SORT_CHART: FlowchartSpec = {
  title: "Merge sort (one call)",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "mergeSort(a)" },
    {
      id: "base",
      type: "decision",
      text: "length <= 1 ?",
      badge: "1",
      note: "The base case. A single element is already sorted, and this is what stops the recursion.",
    },
    { id: "ret", type: "end", text: "return a", note: "Returning here is what lets the level above start merging." },
    {
      id: "split",
      type: "process",
      text: "mid = length / 2",
      note: "The split is positional and never looks at the values, which is why merge sort's cost is identical on sorted, reversed and random input.",
    },
    {
      id: "divide",
      type: "group",
      text: "Divide",
      accent: "violet",
      badge: "2",
      groupLayout: "column",
    },
    {
      id: "left",
      type: "process",
      text: "left = mergeSort(a[0..mid])",
      accent: "violet",
      parentId: "divide",
      note: "This call runs to completion, all the way down and all the way back up, before the right half is touched at all.",
    },
    {
      id: "right",
      type: "process",
      text: "right = mergeSort(a[mid..])",
      accent: "violet",
      parentId: "divide",
      note: "Only reached once the entire left subtree has finished and returned.",
    },
    {
      id: "merge",
      type: "process",
      text: "return merge(left, right)",
      accent: "blue",
      badge: "3",
      note: "Both halves are sorted by now, so one linear pass combines them. All of merge sort's actual work happens here, on the way back up.",
    },
  ],
  edges: [
    { from: "start", to: "base" },
    { from: "base", to: "ret", label: "yes" },
    { from: "base", to: "split", label: "no" },
    { from: "split", to: "left" },
    { from: "left", to: "right" },
    { from: "right", to: "merge" },
  ],
  legend: [
    { label: "start / end", shape: "start", accent: "green" },
    { label: "process", shape: "process", accent: "neutral" },
    { label: "decision", shape: "decision", accent: "copper" },
    { label: "calls itself", shape: "process", accent: "violet" },
    { label: "moves data", shape: "process", accent: "blue" },
  ],
};

export const MERGE_STEP_CHART: FlowchartSpec = {
  title: "The merge step",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "merge(left, right)" },
    { id: "init", type: "process", text: "i = 0, j = 0\nout = []" },
    { id: "both", type: "decision", text: "i < left.len and\nj < right.len ?" },
    {
      id: "cmp",
      type: "decision",
      text: "left[i] <= right[j] ?",
      accent: "amber",
      badge: "!",
      note: "<= and not <. On a tie the left value is taken first, which is exactly what makes merge sort stable. With plain numbers you cannot tell; with records that share a key, you very much can.",
    },
    { id: "takeL", type: "process", text: "out.push(left[i])\ni = i + 1", accent: "blue" },
    { id: "takeR", type: "process", text: "out.push(right[j])\nj = j + 1", accent: "blue" },
    {
      id: "drain",
      type: "group",
      text: "Drain whichever side is left",
      groupLayout: "column",
      note: "At most one of these two does anything.",
    },
    {
      id: "drainL",
      type: "process",
      text: "append rest of left",
      parentId: "drain",
      note: "Whatever is left is already sorted and already larger than everything emitted, so it is copied wholesale rather than compared.",
    },
    { id: "drainR", type: "process", text: "append rest of right", parentId: "drain" },
    { id: "end", type: "end", text: "return out" },
  ],
  edges: [
    { id: "m1", from: "start", to: "init" },
    { id: "m2", from: "init", to: "both" },
    { id: "m3", from: "both", to: "cmp", label: "yes" },
    { id: "m4", from: "both", to: "drainL", label: "no" },
    { id: "m5", from: "cmp", to: "takeL", label: "yes" },
    { id: "m6", from: "cmp", to: "takeR", label: "no" },
    { id: "m7", from: "takeL", to: "both" },
    { id: "m8", from: "takeR", to: "both" },
    { id: "m9", from: "drainL", to: "drainR" },
    { id: "m10", from: "drainR", to: "end" },
  ],
  walkthrough: [
    { node: "start", caption: "Merging left = [27, 38] with right = [3, 9]. Both are already sorted." },
    { node: "init", caption: "Two pointers at the front of each side, and an empty output." },
    { node: "both", caption: "Both sides still have elements ? Yes." },
    { node: "cmp", caption: "left[0] = 27, right[0] = 3. Is 27 <= 3 ? No." },
    { node: "takeR", caption: "Take 3 from the right. out = [3], j moves to 1." },
    { node: "both", caption: "Still both non-empty ? Yes." },
    { node: "cmp", caption: "27 vs 9. Is 27 <= 9 ? No." },
    { node: "takeR", caption: "Take 9. out = [3, 9], j moves to 2 and the right side is now exhausted." },
    { node: "both", caption: "j has run off the end of right, so the loop stops." },
    { node: "drainL", caption: "Copy the rest of the left side across: out = [3, 9, 27, 38]." },
    { node: "drainR", caption: "The right side is empty, so this does nothing." },
    { node: "end", caption: "Four elements out, three comparisons, one pass. That is the whole merge." },
  ],
  interactive: { walkthrough: true },
};

export const QUICK_SORT_CHART: FlowchartSpec = {
  title: "Quick sort (one call)",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "quickSort(a, low, high)" },
    {
      id: "base",
      type: "decision",
      text: "low >= high ?",
      badge: "1",
      note: "A range of zero or one element is already sorted.",
    },
    { id: "ret", type: "end", text: "return" },
    {
      id: "part",
      type: "process",
      text: "p = partition(a, low, high)",
      accent: "blue",
      badge: "2",
      note: "All the work happens here, before the recursion rather than after it. Once this returns, a[p] is in its final position permanently and will never move again.",
    },
    { id: "conquer", type: "group", text: "Conquer", accent: "violet", badge: "3", groupLayout: "column" },
    {
      id: "left",
      type: "process",
      text: "quickSort(a, low, p-1)",
      accent: "violet",
      parentId: "conquer",
      note: "Everything smaller than the pivot.",
    },
    {
      id: "right",
      type: "process",
      text: "quickSort(a, p+1, high)",
      accent: "violet",
      parentId: "conquer",
      note: "Note that p itself is excluded from both calls. Including it would give a range that never shrinks, which is an infinite loop waiting to happen.",
    },
    { id: "end", type: "end", text: "return", note: "There is no merge step. Once both sides return, the range is sorted." },
  ],
  edges: [
    { from: "start", to: "base" },
    { from: "base", to: "ret", label: "yes" },
    { from: "base", to: "part", label: "no" },
    { from: "part", to: "left" },
    { from: "left", to: "right" },
    { from: "right", to: "end" },
  ],
  legend: [
    { label: "start / end", shape: "start", accent: "green" },
    { label: "process", shape: "process", accent: "neutral" },
    { label: "decision", shape: "decision", accent: "copper" },
    { label: "calls itself", shape: "process", accent: "violet" },
    { label: "moves data", shape: "process", accent: "blue" },
  ],
};

export const PARTITION_CHART: FlowchartSpec = {
  title: "Lomuto partition",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "partition(a, low, high)" },
    {
      id: "init",
      type: "process",
      text: "pivot = a[high]\ni = low - 1\nj = low",
      note: "i marks the end of the 'smaller than pivot' region, which starts empty. That is why it starts one before the range rather than at it.",
    },
    { id: "loop", type: "decision", text: "j < high ?" },
    { id: "cmp", type: "decision", text: "a[j] < pivot ?" },
    {
      id: "grow",
      type: "process",
      text: "i = i + 1\nswap a[i], a[j]",
      accent: "blue",
      note: "Grow the smaller region by one and move this element into it. The value displaced was known to be >= pivot, so it lands correctly on the other side.",
    },
    { id: "inc", type: "process", text: "j = j + 1" },
    {
      id: "final",
      type: "process",
      text: "swap a[i+1], a[high]",
      accent: "blue",
      badge: "!",
      note: "Drop the pivot onto the boundary between the two regions. This is the step that makes a[i+1] permanent.",
    },
    { id: "end", type: "end", text: "return i + 1" },
  ],
  edges: [
    { id: "p1", from: "start", to: "init" },
    { id: "p2", from: "init", to: "loop" },
    { id: "p3", from: "loop", to: "cmp", label: "yes" },
    { id: "p4", from: "loop", to: "final", label: "no" },
    { id: "p5", from: "cmp", to: "grow", label: "yes" },
    { id: "p6", from: "cmp", to: "inc", label: "no" },
    { id: "p7", from: "grow", to: "inc" },
    { id: "p8", from: "inc", to: "loop" },
    { id: "p9", from: "final", to: "end" },
  ],
  walkthrough: [
    { node: "start", caption: "Partitioning [7, 2, 4, 6] with low = 0 and high = 3." },
    { node: "init", caption: "pivot = a[3] = 6. i = -1 because the 'smaller' region is empty. j = 0." },
    { node: "loop", caption: "j < high, that is 0 < 3 ? Yes." },
    { node: "cmp", caption: "a[0] = 7. Is 7 < 6 ? No, so it belongs on the far side. Leave it." },
    { node: "inc", caption: "j = 1. Nothing moved." },
    { node: "loop", caption: "1 < 3 ? Yes." },
    { node: "cmp", caption: "a[1] = 2. Is 2 < 6 ? Yes, it belongs in the smaller region." },
    { node: "grow", caption: "i becomes 0, swap a[0] and a[1]. The array is now [2, 7, 4, 6]." },
    { node: "inc", caption: "j = 2." },
    { node: "loop", caption: "2 < 3 ? Yes." },
    { node: "cmp", caption: "a[2] = 4. Is 4 < 6 ? Yes." },
    { node: "grow", caption: "i becomes 1, swap a[1] and a[2]. The array is now [2, 4, 7, 6]." },
    { node: "inc", caption: "j = 3." },
    { node: "loop", caption: "3 < 3 ? No. The scan is finished, and i = 1 marks the end of the smaller region." },
    { node: "final", caption: "Swap a[i+1] = a[2] with the pivot at a[3]. The array is [2, 4, 6, 7]." },
    { node: "end", caption: "Return 2. a[2] = 6 is now permanently correct, with smaller left and larger right." },
  ],
  interactive: { walkthrough: true },
};

export const HEAP_SORT_CHART: FlowchartSpec = {
  title: "Heap sort",
  direction: "LR",
  lanes: [
    { id: "build", label: "Build the heap" },
    { id: "extract", label: "Extract, repeatedly" },
  ],
  nodes: [
    { id: "start", type: "start", text: "Start", lane: "build" },
    {
      id: "buildinit",
      type: "process",
      text: "i = n/2 - 1",
      lane: "build",
      note: "The last internal node. Everything after it is a leaf, and a leaf is already a valid heap, so there is nothing to do to them.",
    },
    { id: "buildloop", type: "decision", text: "i >= 0 ?", lane: "build" },
    { id: "sift1", type: "process", text: "siftDown(a, i, n-1)", accent: "blue", lane: "build" },
    { id: "dec-i", type: "process", text: "i = i - 1", lane: "build" },
    {
      id: "endinit",
      type: "process",
      text: "end = n - 1",
      lane: "extract",
      badge: "2",
      note: "The heap is built, and it took O(n), not O(n log n). Now repeatedly extract the maximum.",
    },
    { id: "sortloop", type: "decision", text: "end > 0 ?", lane: "extract" },
    {
      id: "swap",
      type: "process",
      text: "swap a[0], a[end]",
      accent: "blue",
      lane: "extract",
      note: "a[0] is the largest remaining value, and a[end] is exactly where it belongs. One swap finalises one element.",
    },
    {
      id: "sift2",
      type: "process",
      text: "siftDown(a, 0, end-1)",
      accent: "blue",
      lane: "extract",
      note: "Restore the heap over the shrunken range. The element just placed is outside it now, so it is never touched again.",
    },
    { id: "dec-end", type: "process", text: "end = end - 1", lane: "extract" },
    { id: "end", type: "end", text: "Sorted", lane: "extract" },
  ],
  edges: [
    { from: "start", to: "buildinit" },
    { from: "buildinit", to: "buildloop" },
    { from: "buildloop", to: "sift1", label: "yes" },
    { from: "buildloop", to: "endinit", label: "no" },
    { from: "sift1", to: "dec-i" },
    { from: "dec-i", to: "buildloop" },
    { from: "endinit", to: "sortloop" },
    { from: "sortloop", to: "swap", label: "yes" },
    { from: "sortloop", to: "end", label: "no" },
    { from: "swap", to: "sift2" },
    { from: "sift2", to: "dec-end" },
    { from: "dec-end", to: "sortloop" },
  ],
};

export const COUNTING_SORT_CHART: FlowchartSpec = {
  title: "Counting sort",
  direction: "LR",
  lanes: [
    { id: "count", label: "Count" },
    { id: "write", label: "Write back" },
  ],
  nodes: [
    { id: "start", type: "start", text: "Start", lane: "count" },
    {
      id: "alloc",
      type: "process",
      text: "counts = array of k zeros",
      lane: "count",
      accent: "amber",
      note: "One bucket per possible value. This is why k must be small: the memory bill is the size of the value range, not the size of the input.",
    },
    { id: "countinit", type: "process", text: "i = 0", lane: "count" },
    { id: "countloop", type: "decision", text: "i < n ?", lane: "count" },
    {
      id: "tally",
      type: "process",
      text: "counts[a[i]] += 1\ni = i + 1",
      accent: "blue",
      lane: "count",
      badge: "!",
      note: "No comparison happens anywhere in this algorithm. The value is used directly as an index, which is how counting sort dodges the O(n log n) lower bound entirely.",
    },
    { id: "writeinit", type: "process", text: "write = 0\nvalue = 0", lane: "write" },
    { id: "outer", type: "decision", text: "value < k ?", lane: "write" },
    { id: "inner", type: "decision", text: "counts[value] > 0 ?", lane: "write" },
    {
      id: "emit",
      type: "process",
      text: "a[write] = value\nwrite += 1\ncounts[value] -= 1",
      accent: "blue",
      lane: "write",
    },
    { id: "next", type: "process", text: "value = value + 1", lane: "write" },
    { id: "end", type: "end", text: "Sorted", lane: "write" },
  ],
  edges: [
    { from: "start", to: "alloc" },
    { from: "alloc", to: "countinit" },
    { from: "countinit", to: "countloop" },
    { from: "countloop", to: "tally", label: "yes" },
    { from: "countloop", to: "writeinit", label: "no" },
    { from: "tally", to: "countloop" },
    { from: "writeinit", to: "outer" },
    { from: "outer", to: "inner", label: "yes" },
    { from: "outer", to: "end", label: "no" },
    { from: "inner", to: "emit", label: "yes" },
    { from: "inner", to: "next", label: "no" },
    { from: "emit", to: "inner" },
    { from: "next", to: "outer" },
  ],
};

export const SORTING_CHARTS: Record<string, FlowchartSpec> = {
  bubble: BUBBLE_SORT_CHART,
  selection: SELECTION_SORT_CHART,
  insertion: INSERTION_SORT_CHART,
  merge: MERGE_SORT_CHART,
  "merge-step": MERGE_STEP_CHART,
  quick: QUICK_SORT_CHART,
  partition: PARTITION_CHART,
  heap: HEAP_SORT_CHART,
  counting: COUNTING_SORT_CHART,
};

/** A small starting chart for the maker tool. */
export const STARTER_CHART: FlowchartSpec = {
  title: "Untitled flowchart",
  direction: "LR",
  nodes: [
    { id: "start", type: "start", text: "Start" },
    { id: "step", type: "process", text: "Do something" },
    { id: "check", type: "decision", text: "Condition ?" },
    { id: "again", type: "process", text: "Try again" },
    { id: "end", type: "end", text: "End" },
  ],
  edges: [
    { from: "start", to: "step" },
    { from: "step", to: "check" },
    { from: "check", to: "end", label: "yes" },
    { from: "check", to: "again", label: "no" },
    { from: "again", to: "step" },
  ],
};
